title: Suchit Prakash Chakranarayan
logo: "/suchit.jpeg"
description: >
  <br>
  Artificial Intelligence Enthusiast | Experience in information technology | R | Data science | Machine Learning | Python Developer | AWS | Full Stack Developer
  <br>
  <a href="https://www.linkedin.com/in/suchit-chakranarayan/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:suchitchakranarayan1@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
